### ISSUE TITLE
CMP reprompt in every page on IE11 

### ISSUE THREAD

**Issue by davideperfetto** [IABTechLab/cmp#188]
CMP reprompt after consent  for every  webpage on IE11, but works correctly on Edge.

**Comment by samtingleff** [comment]
Thanks @DavideMoney. Can you share the configuration used? Or point to a page where this occurs?

**Comment by DavideMoney** [comment]
@samtingleff sorry for the late reply.
Example page
https://www.digital-forum.it

Thanks
